# Copyright (C) 2026 Thomas
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os
from datetime import datetime
from jinja2 import Template
from weasyprint import HTML, CSS

# Basic HTML Template for the Report
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thermal Bridge Simulation Report</title>
    <style>
        @page {
            size: A4;
            margin: 2cm;
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
                font-family: 'Helvetica', sans-serif;
                font-size: 9pt;
            }
        }
        body {
            font-family: 'Helvetica', sans-serif;
            color: #333;
            line-height: 1.5;
        }
        header {
            border-bottom: 2px solid #0056b3;
            padding-bottom: 10px;
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        header h1 {
            color: #0056b3;
            margin: 0;
            font-size: 24pt;
        }
        header .meta {
            text-align: right;
            font-size: 10pt;
            color: #777;
        }
        section {
            margin-bottom: 30px;
        }
        h2 {
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
            color: #444;
            margin-top: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f9f9f9;
            font-weight: bold;
        }
        .result-highlight {
            background-color: #e6f3ff;
            font-weight: bold;
        }
        .image-container {
            text-align: center;
            margin: 20px 0;
            border: 1px solid #eee;
            padding: 10px;
        }
        img {
            max-width: 100%;
            height: auto;
        }
        footer {
            margin-top: 50px;
            font-size: 9pt;
            color: #777;
            text-align: center;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>

<header>
    <div>
        <h1>Thermal Report</h1>
        <div style="font-size: 14pt; margin-top: 5px;">{{ project_name }}</div>
    </div>
    <div class="meta">
        <div>Date: {{ date }}</div>
        <div>Author: {{ author }}</div>
    </div>
</header>

<section>
    <h2>Project Description</h2>
    <p>{{ description }}</p>
</section>

<section>
    <h2>Simulation Results</h2>
    <table>
        <thead>
            <tr>
                <th>Parameter</th>
                <th>Value</th>
                <th>Unit</th>
            </tr>
        </thead>
        <tbody>
            {% for key, value in results.items() %}
            <tr class="{% if key in ['Psi', 'fRsi'] %}result-highlight{% endif %}">
                <td>{{ key }}</td>
                <td>{{ value }}</td>
                <td>
                    {% if key == 'Psi' %}W/(m·K)
                    {% elif 'Temp' in key %}°C
                    {% elif key == 'fRsi' %}-
                    {% else %}-{% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>

<section>
    <h2>Temperature Field</h2>
    <div class="image-container">
        <img src="{{ image_src }}" alt="Temperature Map">
    </div>
</section>

<footer>
    Generated by Thermal Bridge Simulator
</footer>

</body>
</html>
"""

def generate_pdf_report(project_name, author, description, results, image_path, output_path=None):
    """
    Generates a PDF report from simulation results.
    
    If output_path is None, returns (True, BytesIO buffer) instead of writing to disk.
    If output_path is provided, writes to disk and returns (True, "success message").
    """
    
    import base64
    from io import BytesIO

    img_src = ""
    if image_path:
        if isinstance(image_path, str) and os.path.exists(image_path):
             img_src = f"file://{os.path.abspath(image_path)}"
        elif hasattr(image_path, 'read') or isinstance(image_path, bytes):
             # It's a buffer or bytes
             if hasattr(image_path, 'read'):
                 if hasattr(image_path, 'seek'): image_path.seek(0)
                 data = image_path.read()
             else:
                 data = image_path
             b64_data = base64.b64encode(data).decode('utf-8')
             img_src = f"data:image/png;base64,{b64_data}"
    
    # 1. Prepare Context
    context = {
        "project_name": project_name,
        "author": author,
        "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "description": description,
        "results": results,
        "image_src": img_src
    }
    
    # 2. Render HTML
    template = Template(HTML_TEMPLATE)
    html_content = template.render(context)
    
    # 3. Write PDF (to file or in-memory buffer)
    try:
        if output_path is None:
            # Return in-memory buffer (for multi-user / cloud hosting safety)
            pdf_buffer = BytesIO()
            HTML(string=html_content).write_pdf(pdf_buffer)
            pdf_buffer.seek(0)
            return True, pdf_buffer
        else:
            HTML(string=html_content).write_pdf(output_path)
            return True, "Report generated successfully."
    except Exception as e:
        return False, f"Failed to generate report: {str(e)}"

if __name__ == "__main__":
    # Test stub
    test_results = {"Psi": 0.15, "fRsi": 0.72, "Min Surface Temp": 12.6}
    generate_pdf_report("Test Project", "Tester", "This is a test run.", test_results, "preview.png", "test_report.pdf")
    print("Test report generated: test_report.pdf")
